import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useRouter } from 'next/router'
import { motion } from 'framer-motion'
import Bodies from './components/bobies'
import Pay from './pay'
import Info from './info'
export default function Home() {
  const router = useRouter()
  return (
    <div >
      <Head>
        <title>Tesol</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='flex justify-center lg:h-50'>
        
        <div className=' flex flex-row justify-between text-center absolute  my-2 grid-cols-3 bg-white shadow-md py-1  w-10/12  '>
            <motion.img alt='logo' src='/TESOL+Tree+Logo+Colour.png' className="top-1 left-1 w-20 h-20 cursor-pointer" onClick={()=>router.push('/')} />
            <div className='flex flex-row p-4 text-center font-bold'>
                <p onClick={()=>{router.push('/?pay=1&title=2') /* paywithmaxi()*/}} className='cursor-pointer bg-cyan-400 p-2 shadow-lg rounded-lg'>PAYMENT</p>
                <p className='cursor-pointer bg-cyan-400 grid-cols-9 mx-2 p-2 shadow-lg rounded-lg'>MY ACOUNT</p>
            </div>
        </div>
        
    </div>
    
    <div>{router.query.title ? (<Info/>) : (<Bodies/>)}</div>
    

    </div>
  )
}

const paywithmaxi = async () =>{
      const data = { 
      PayType : 'MaxiCash',
      Amount : 1000, //please note that the amounts must be sent in Cents
      Currency : 'maxiDollar', //values can be “maxiDollar” or “maxiRand”
      Telephone : '+243995714871',
      MerchantID : '560e9cefb3ff4d0784d85f3cf752ee02',
      MerchantPassword : '432d3d0d229b4469b9053e4fbde0bedc',
      Language : 'en', //en or fr
      Reference : 'school fees payment' };

      var payloadString = "";
      payloadString = JSON.stringify(data);
      payloadString = payloadString.replace(/\"/g, '\\"');

    await fetch('https://api-testbed.maxicashapp.com/Merchant/api.asmx/PayNowSynch', {
      method: 'POST', // or 'PUT'
      headers: {
        'Content-Type': 'application/json; charset=utf-8',
      },
      body: '{strData: "' + payloadString + '" }',
    })
    .then(response => response.json())
    .then(data => {
      console.log('Success:', data);
    })
    .catch((error) => {
      console.error('Error:', error);
    });
}
